- Gemfile
- Gemfile.lock
> updates to geoblacklight 0.5.0 and blacklight 5.8.2

- config/solr_configs/solrconfig.xml
See geoblacklight/geoblacklight#258
> tweek solr config to address geoblacklight/geoblacklight#258

- Gemfile
- Gemfile.lock
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_show_message.html.erb
- spec/features/unavailable_layer_spec.rb
- spec/fixtures/solr_documents/actual-papermap1.json
- spec/fixtures/solr_documents/actual-point1.json
- spec/fixtures/solr_documents/actual-polygon1.json
- spec/fixtures/solr_documents/actual-raster1.json
- spec/fixtures/solr_documents/harvard-unavailable.json
- spec/fixtures/solr_documents/harvard_raster.json
- spec/fixtures/solr_documents/public_iiif_princeton.json
- spec/fixtures/solr_documents/public_polygon_mit.json
- spec/fixtures/solr_documents/restricted-line.json
Closes #147 
Also updates to GeoBlacklight 0.5.1 and adds over new GeoBlacklight fixtures (with an additional one added to test for unavailable message)
> Add unavailable message

- app/assets/stylesheets/modules/top_navbar.css.scss
- app/views/_user_util_links.html.erb
- app/views/shared/_top_navbar.html.erb
- spec/features/top_navbar_spec.rb
> moves to revs login/logout pattern

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/bootstrap-variables.css.scss
- app/assets/stylesheets/modules/leaflet.css.scss
> add SU preferred font Source Sans Pro

- app/views/catalog/_show_default.html.erb
- app/views/layouts/earthworks.html.erb
- config/locales/blacklight.en.yml
- spec/features/page_title_spec.rb
> add in some custom page titles

- config/initializers/blacklight_initializer.rb
Removes SMS and cite since they both are not doing anything.
> removes sms and cite

- app/controllers/catalog_controller.rb
> temporarily remove collection facet

- app/assets/stylesheets/bootstrap-variables.css.scss
- app/assets/stylesheets/earthworks.css.scss
- app/assets/stylesheets/modules/base_styles.scss
- app/assets/stylesheets/modules/facets.scss
- app/assets/stylesheets/modules/header_navbar.css.scss
- app/assets/stylesheets/modules/top_navbar.css.scss
- app/assets/stylesheets/sul-variables.css.scss
- app/views/layouts/earthworks.html.erb
- app/views/shared/feedback_forms/_form.html.erb
Adds in `h1`'s
Underlines to anchor tags
Updating colors/styles
Hidden inputs for hidden inputs
> adds updated styling for accessibility

- Gemfile
- Gemfile.lock
- app/controllers/catalog_controller.rb
- config/locales/blacklight.en.yml
Updates to the latest version of GeoBlacklight
> update to geoblacklight 0.6.0

- app/assets/stylesheets/bootstrap-variables.css.scss
- app/assets/stylesheets/modules/top_navbar.css.scss
> update topnav dropdown styles

- app/assets/stylesheets/modules/home.css.scss
- config/locales/geoblacklight.en.yml
> update some heading on home page

- Capfile
- config/deploy.rb
Temporary patch until we can resolve the squash notifier #219
> comment out squash temporarily

- app/views/shared/_su_footer.html.erb
> fix typo in footer link

- Gemfile
- Gemfile.lock
- config/newrelic.yml
- config/settings.yml
Adds in newrelic to monitor our applications. Configs already created on stage and prod boxes and tested on stage successfully.
Closes #216
> Newrelic install

- spec/integration/external-data/author_search_spec.rb
I think some of the metadata may have changed on this.
> fix integration tests

- Gemfile
- Gemfile.lock
deployed successfully to stage
> update to geoblacklight 0.8.0

- app/views/layouts/earthworks.html.erb
- app/views/shared/_sitelinks_search_box.html.erb
From: https://developers.google.com/structured-data/slsb-overview
> adds in Google SiteLinks search

- Gemfile
- Gemfile.lock
- app/models/search_builder.rb
- app/models/solr_document.rb
Fixes #231 by allowing configuration
> update blacklight to 5.12.1 and geoblacklight to 0.9.0

- app/assets/stylesheets/earthworks.css.scss
- app/assets/stylesheets/modules/zero_results.scss
- app/views/catalog/_zero_results.html.erb
- spec/features/zero_results_spec.rb
For a better experience when users get zero results, hopefully will drive requests to feedback
> adds feedback link to zero results page

- config/deploy.rb
Really should have been part of #240
> link blacklight-yml

- Gemfile
- Gemfile.lock
Fixes an issue with the GeoBlacklight SearchBuilder
> update to geoblacklight 0.9.2

- app/assets/stylesheets/modules/typeahead.scss
> fixes zindex issue for search bar

- Gemfile.lock
Updating some deployment, and security dependencies
> Update cap rails and uglifier

- app/views/catalog/_zero_results.html.erb
Also allowed for an error with a carefully crafted request.
> no need to keep this here since we dont provide multiple search fields

- app/controllers/wms_controller.rb
- spec/controllers/wms_controller_spec.rb
This PR re-enables WFS info handling which was broken by some GeoBlacklight updates and a previous PR of mine :cry:
> Re-add handle

- config/deploy/production.rb
- config/deploy/production_all.rb
- config/deploy/stage.rb
Spring and other things are being deployed in prod. This fixes that which hopefully should reduce some of the memory footprint.
> bundle without development for stage and prod

- Gemfile
- config/deploy/dev.rb
- config/deploy/prod.rb
- config/deploy/stage.rb
@mejackreed this cleans up the deploys a bit and puts stage into production mode
> fix deploy packages and set dev/stage to RAILS_ENV=production

- app/views/catalog/_show_default.html.erb
- app/views/layouts/earthworks.html.erb
- spec/features/canonical_urls_spec.rb
> add link[rel="canonical"] for Stanford layers

- Gemfile
- Gemfile.lock
- lib/tasks/geo_combine.rake
- scripts/indexing/ogp/.gitignore
- scripts/indexing/ogp/README.md
- scripts/indexing/ogp/download.rb
- scripts/indexing/ogp/to_geoblacklight.rb
- scripts/indexing/ogp/validate.rb
@mejackreed This PR adds the OGP indexing pipeline -- see scripts/indexing/ogp/README.md
> OGP download and validation scripties

- README.md
- spec/features/bookmarks_spec.rb
- spec/features/saved_searches_spec.rb
- spec/mailers/feedback_mailer_spec.rb
- spec/spec_helper.rb
This fixes the coveralls reporting
> update to put simplecov at the very top

- config/initializers/sidekiq.rb
- config/settings.yml
> add REDIS configuration for GeoMonitor sidekiq

- Gemfile.lock
- README.md
- lib/tasks/earthworks.rake
This PR is connected to #337 and depends on https://github.com/OpenGeoMetadata/GeoCombine/pull/84
> OpenGeoMetadata indexing pipeline

- config/environments/production.rb
We're currently seeing DEBUG logging in production. Note that this change will affect stage and prod...
> INFO logging in production

- app/helpers/application_helper.rb
- spec/features/unavailable_layer_spec.rb
> do not show the unavailable message on iiif layers

- .solr_wrapper
- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/prod.rb
- config/schedule.rb
Closes #401 
I haven't tested this yet, but I used the roles so that we weren't enqueuing jobs from each node.
> setup geomonitor to run periodically using whenever gem

- app/models/solr_document.rb
- app/views/catalog/_show_message.html.erb
- config/locales/en.yml
- config/settings.yml
> modify the unavailability messaging

- Gemfile.lock
- app/assets/javascripts/geoblacklight.js
- app/assets/stylesheets/geoblacklight.scss
- app/assets/stylesheets/modules/leaflet.scss
- app/views/catalog/_show_default.html.erb
- spec/fixtures/solr_documents/stanford-ts545zc6250.json
Adds index map functionality and fixes an issue with modal responsiveness
> update geoblacklight to v1.8.0

- Gemfile
- Gemfile.lock
> Repin bootstrap until OS situtation is sorted

- Gemfile
- Gemfile.lock
This reverts commit b2765ef75e594f38f3de0ea6c8c0d9eef85b50e3.
With https://github.com/sul-dlss/operations-tasks/issues/1824#issuecomment-453284799, we should be good to go.
> Revert "Repin bootstrap until OS situtation is sorted"

- config/settings.yml
> Add ArcGIS base url setting

- app/views/shared/feedback_forms/_form.html.erb
> Remove useless class

- scripts/geoserver/set_raster_styles.rb
Used to resolve the data corruption documented in https://github.com/sul-dlss/gis-robot-suite/issues/224
> Script used to remediate rasters that have corrupted styles

- config/settings.yml
> Add iiif to web services shown

- Gemfile
- Gemfile.lock
- config/initializers/rack_attack.rb
- config/schedule.rb
- config/settings.yml
- lib/tasks/earthworks.rake
Same implementation as SearchWorks.
> Add rack-attack to throttle requests

- lib/tasks/earthworks.rake
@cbeer is this what you were thinking? Or something different?
> Bump up the random spacing for layer checking

- Gemfile
- Gemfile.lock
- app/controllers/feedback_forms_controller.rb
- app/views/shared/feedback_forms/_form.html.erb
- config/initializers/recaptcha.rb
- config/settings.yml
- spec/controllers/feedback_forms_controller_spec.rb
- spec/rails_helper.rb
- spec/support/stub_current_user.rb
I wasn't able to get recaptcha v3 working so just went with the SW implementation of v2
> Add reCaptcha v2

- config/initializers/okcomputer.rb
- config/settings.yml
> Check DOWNLOAD_PATH (when set) in OK Computer

- app/views/catalog/_home_text.html.erb
- app/views/shared/_su_footer.html.erb
> Accessibility tweaks

- Gemfile
- Gemfile.lock
So we can ship the GeoBlacklight updates to prod throughout this workcycle.
> Update Blacklight/GeoBlacklight and point GeoBlacklight to master

- app/models/user.rb
- config/schedule.rb
- lib/tasks/earthworks.rake
- spec/models/user_spec.rb
> Add a rake task to prune guest users and schedule to run nightly

- app/controllers/catalog_controller.rb
- config/initializers/rack_attack.rb
Hoping this will make https://github.com/OpenGeoMetadata/edu.stanford.purl/pull/39 more resiliant
> Tweaks for API consumers

- Gemfile
- Gemfile.lock
- app/controllers/restricted_proxy_controller.rb
- config/routes.rb
- spec/controllers/restricted_proxy_controller_spec.rb
Rather than proxy content through Apache, just proxy through the application to reduce shib errors.
Shared Configs PR here: https://github.com/sul-dlss/shared_configs/pull/1419
> Fixes #547 by proxying content through the application

- Gemfile.lock
- app/helpers/application_helper.rb
- app/models/solr_document.rb
- config/settings.yml
- spec/fixtures/solr_documents/collection.json
- spec/fixtures/solr_documents/part_of_collection.json
Just to support @ggeisler and the teams continued work on this feature
> Add collection fixtures for usage in our feature development + update geoblacklight

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/stage.rb
> Update to sidekiq6

- app/assets/stylesheets/earthworks.scss
- app/assets/stylesheets/modules/feedback_form.scss
- app/assets/stylesheets/modules/top_navbar.scss
- app/models/user.rb
- app/views/shared/_top_navbar.html.erb
- app/views/shared/feedback_forms/_form.html.erb
- spec/models/user_spec.rb
> Update  topnav layout and styling

- app/assets/stylesheets/modules/feedback_form.scss
- app/views/shared/feedback_forms/_form.html.erb
- app/views/shared/feedback_forms/_reporting_from.html.erb
> Re-layout the feedback form;

- app/views/layouts/blacklight/base.html.erb
> Add skip links from upstream

- app/assets/stylesheets/blacklight.scss
- app/assets/stylesheets/bootstrap-overrides.scss
- app/assets/stylesheets/bootstrap-variables.scss
- app/assets/stylesheets/modules/base_styles.scss
- app/assets/stylesheets/modules/facets.scss
> Update colors for contrast

- app/views/catalog/_rights_metadata.html.erb
> Hide license images

- app/views/shared/_header_navbar.html.erb
> Make #search-navbar a simple div

- app/assets/stylesheets/bootstrap-overrides.scss
- app/assets/stylesheets/bootstrap-variables.scss
- app/assets/stylesheets/geoblacklight.scss
> Fix the primary color override

- Gemfile.lock
- app/controllers/catalog_controller.rb
- config/locales/blacklight.en.yml
- config/settings.yml
Discussed the title and heading w/ @ggeisler and he 👍
> Enable citation in earthworks fixes #594

- app/assets/stylesheets/bootstrap-variables.scss
> Increase the small font size

- lib/tasks/earthworks.rake
Part of #591 will wait for GIS team to review on stage
> Add Cornell OGM data

- app/assets/stylesheets/modules/sul_footer.scss
- app/assets/stylesheets/modules/top_navbar.scss
- app/views/shared/_su_footer.html.erb
- app/views/shared/_top_navbar.html.erb
> Layout updates

- app/assets/stylesheets/bootstrap-variables.scss
> Update the font fallbacks for better diacritics

- app/mailers/application_mailer.rb
- app/mailers/feedback_mailer.rb
Because of https://github.com/projectblacklight/blacklight/commit/2a881c1af03a5db595da93b383edcd1505073eec
> Setup ApplicationMailer

- app/controllers/catalog_controller.rb
See https://github.com/geoblacklight/geoblacklight/pull/990/commits/4610b818a0b5c0c75bcece4937dd5cd8b4ec7c43
Fixes #794
> Explicitly define the source as a facet field

- .rubocop.yml
This keeps the build from randomly failing after a bundle update.  We will now be intentional about when we want to add new cops
> Be explicit about which rubocops we care about

- Gemfile
- Gemfile.lock
> upgrade Sidekiq and Redis gems

- .rubocop.yml
- app/controllers/catalog_controller.rb
- lib/legacy_id_map.rb
- spec/features/bookmarks_spec.rb
- spec/features/feedback_form_spec.rb
- spec/features/search_spec.rb
- spec/integration/external-data/author_search_spec.rb
- spec/integration/external-data/geo_search_spec.rb
- spec/lib/earthworks/harvester_spec.rb
Also activates available rubocop plugins.
> Update cops and reformat with rubocop

- Jenkinsfile
This reverts commit 1602a5e219b10cbd34160e933b70a02bdc0f23b2.
> Revert "Decouple CD for stage/UAT and connect to Geoblacklight v4 branch"

- config/solr_configs/solrconfig.xml
See https://github.com/sul-dlss/sul-solr-configs/pull/331
> Remove unused healthcheck file configuration for solr

- app/models/user.rb
- config/initializers/devise.rb
- spec/models/user_spec.rb
> Pull over User#shibboleth_groups implementation from exhibits.

- app/models/user.rb
- app/views/shared/feedback_forms/_form.html.erb
- config/initializers/devise.rb
closes #166 
Logged out
Logged in
> autopopulate username and email to feedback form

- config/settings.yml
> enable IIIF drag and drop link

- config/initializers/okcomputer.rb
Pretty sure this is right. Not 100%
> fix blacklight solr url location

- config/importmap.rb
> use bootstrap.bundle instead of bootstrap

- app/assets/stylesheets/application.css
- app/assets/stylesheets/geoblacklight.scss
- app/views/shared/_footer.html.erb
> add footer

- Jenkinsfile
Temporary measure while we work on the UI upgrades.
> Connect bl8 branch to continuous deployment to UAT

- Gemfile.lock
- app/assets/stylesheets/application.css
- app/assets/stylesheets/earthworks.css
- app/components/earthworks/recently_added_list.html.erb
- app/components/earthworks/recently_added_list.rb
- app/components/geoblacklight/header_component.html.erb
- app/components/geoblacklight/header_component.rb
- app/views/catalog/_home_text.html.erb
- config/locales/en.yml
> Bl8 homepage

- app/assets/stylesheets/earthworks.css
> add box shadow, center titles

- app/assets/stylesheets/earthworks.css
- app/components/earthworks/header_icons_component.html.erb
- app/components/earthworks/search_result_component.rb
> small header icons fixes search page

- app/components/earthworks/document_component.html.erb
> add header icons to show page

- config/settings.yml
> update index map colors

- config/settings.yml
- lib/earthworks/harvester.rb
- spec/lib/earthworks/harvester_spec.rb
Closes https://github.com/sul-dlss/earthworks/issues/1138
I've not worked with the harvester before, so I welcome feedback if this is off base!
> Filter dcat_theme_sm during OGM harvesting using controlled vocabulary

- app/assets/stylesheets/earthworks.css
- app/controllers/catalog_controller.rb
- app/views/catalog/_home_text.html.erb
> Use container-fluid and set max-width to 1600px

- app/components/earthworks/download_links_component.html.erb
- app/components/earthworks/download_links_component.rb
hgl got removed from geoblacklight https://github.com/geoblacklight/geoblacklight/pull/1518. Closes #1158
> remove hgl

- app/components/earthworks/download_links_component.html.erb
- app/components/earthworks/header_icons_component.html.erb
> fix header icons, download headings 

- app/components/blacklight/top_navbar_component.html.erb
> update navbar boomarkmarks link

- app/assets/stylesheets/earthworks.css
- app/views/catalog/_home_text.html.erb
> update map height, remove gis tools

- app/assets/stylesheets/earthworks.css
> update header/footer margin to match main container

- app/components/blacklight/icons/other_component.rb
> add other icon

- app/assets/stylesheets/earthworks.css
> update pagination css to be links

- app/assets/stylesheets/earthworks.css
> update search bar background

- app/assets/config/manifest.js
This should have been removed with switching to propshaft.
See https://github.com/rails/propshaft/blob/main/UPGRADING.md\#3-migrate-from-sprockets-to-propshaft
> Remove manifest

- app/assets/stylesheets/earthworks.css
> Make the resource type darker for accessibility purposes

- app/assets/stylesheets/earthworks.css
> increase padding for pagination

- app/components/earthworks/download_links_component.html.erb
closes #1264 
When reviewing use hide whitespace. It was only two lines of code changes.
> add download controller

- config/solr_configs/schema.xml
See https://github.com/sul-dlss/sul-solr-configs/pull/333
> Add the *_ssi dynamic field type for storing hashed IDs

- app/assets/stylesheets/earthworks.css
- app/javascript/application.js
> 911 zoom level

- app/assets/stylesheets/earthworks.css
> decrease padding on mobile

- app/views/catalog/_document_split.html.erb
> update column widths on search page

- app/components/blacklight/start_over_button_component.rb
- spec/components/blacklight/start_over_button_component_spec.rb
- spec/rails_helper.rb
> Override Blacklight's StartOverButtonComponent

- app/assets/stylesheets/earthworks.css
- app/components/earthworks/search_result_component.html.erb
- app/views/catalog/_document_split.html.erb
- config/locales/blacklight.en.yml
> add bookmark to search results

- app/assets/stylesheets/earthworks.css
- app/components/earthworks/search_result_component.html.erb
> update hover to include description

- app/assets/stylesheets/earthworks.css
> update codesnippet font-size

- app/components/earthworks/document_component.html.erb
- app/components/earthworks/document_component.rb
- app/helpers/earthworks_blacklight_helper.rb
- app/views/layouts/catalog_result.html.erb
> move title to span metadata and map

- app/components/blacklight/top_navbar_component.html.erb
> rename history to search history

- app/assets/stylesheets/earthworks.css
closes [#1311](https://github.com/sul-dlss/earthworks/issues/1311)
> make header tools underlined

- app/controllers/catalog_controller.rb
> reorder and rename facets

- app/assets/stylesheets/earthworks.css
> switch to arrow-circle-fill

- config/code_samples/vector_leaflet.txt
- config/code_samples/vector_python.txt
What this pull request does: 
For leaflet code for vector datasets, adds missing ampersand.
For python code for vector datasets, adds import statements and changes the sequence of the steps - with "load the features" now coming after "send a get request". 
closes #1297
> updating python and leaflet code for code snippets

- app/helpers/earthworks_blacklight_helper.rb
> update facets to col-lg-2

- app/assets/stylesheets/earthworks.css
With this we can close [#1279](https://github.com/sul-dlss/earthworks/issues/1279)
> Shrink the magnifying glass icon

- app/assets/stylesheets/earthworks.css
> remove underline for header tools

- app/assets/stylesheets/earthworks.css
- app/controllers/bookmarks_controller.rb
- app/views/bookmarks/_clear_bookmarks_widget.html.erb
- app/views/bookmarks/index.html.erb
Addresses (but may not close) https://github.com/sul-dlss/earthworks/issues/1301
> Customize bookmarks page layout

- Jenkinsfile
This reverts commit dddb911a31210d531c794bac6d5d00434cbf77d1.
> Revert "Connect bl8 branch to continuous deployment to UAT"

- app/views/layouts/blacklight/base.html.erb
- app/views/shared/_footer.html.erb
> update component library

- app/controllers/catalog_controller.rb
> fix rebase for header tools

- app/components/also_available_component.html.erb
- app/components/document/sidebar_component.html.erb
- app/components/document/sidebar_component.rb
> move also available to own box

- app/helpers/earthworks_geoblacklight_helper.rb
closes #1370 
got undone with https://github.com/sul-dlss/earthworks/commit/26a6933f04f1e785350dd52833e7f6477afde299
> fix document_available? to inherit from geoblacklight

- app/assets/stylesheets/earthworks.css
- app/components/facet_group_component.html.erb
> update facets button on mobile

- app/components/document/sidebar_component.html.erb
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
> no empty sidebar, codesnippets only when dataset

- app/components/recently_added_list_component.html.erb
> Add margin to homepage recently added h2s

- app/assets/stylesheets/earthworks.css
Closes #1379
Homepage:
Search results:
Search results (small):
> Allow the search form to fill its column on the home page

- app/assets/stylesheets/earthworks.css
- app/components/document_metadata_component.rb
> add su-underline to metadata links and update hover behaivor

- app/assets/stylesheets/earthworks.css
> update pagination color

- app/controllers/catalog_controller.rb
> add subject as hidden facet field

- Gemfile
- Gemfile.lock
> Pin geoblacklight to v5.0.0-alpha.10

- app/controllers/catalog_controller.rb
- app/helpers/earthworks_blacklight_helper.rb
- app/models/solr_document.rb
- spec/features/more_details_spec.rb
> Prevent non-URLs from being hyperlinked in dct_identifier_sm

- Gemfile
- Gemfile.lock
- Rakefile
- package-lock.json
> Update Geoblacklight to v5.0.0-alpha.11

- Gemfile
- Gemfile.lock
We use the one in node_modules
> Stop using the bootstrap gem

- app/components/blacklight/top_navbar_component.html.erb
Ref https://github.com/sul-dlss/component-library/pull/81
> Left justify application title on mobile

- .github/workflows/ruby.yml
> Test on ruby 3.4

- app/views/layouts/blacklight/base.html.erb
This will fix the color in the active dropdown menu
> Upgrade to latest component library

- config/initializers/rack_attack.rb
> Rubocop fixes for rack_attack initializer

- app/assets/stylesheets/earthworks.css
> fix alignment for active facets

- Gemfile
- Gemfile.lock
- config/initializers/cors.rb
See https://github.com/sul-dlss/SearchWorks/issues/4805
> Add CORS headers to / so that Searchworks can query

- package-lock.json
- package.json
We aren't using it to bundle anything.
> Remove Vite

- app/components/document/sidebar_component.rb
- app/components/static_map_component.rb
> display static map component for all iiif content

- app/assets/stylesheets/earthworks.css
> fix download buttons to have padding, capitalization, left alignment

- Gemfile
- Gemfile.lock
- app/consumers/sdr_consumer.rb
- app/services/cocina_service.rb
- app/services/solr_service.rb
- config/settings.yml
- spec/consumers/sdr_consumer_spec.rb
Ref #1534
This also stubs out some services that the consumer will call (or a job might end up calling) for testing purposes.
> Implement a racecar consumer for SDR indexing messages
