sul-dlss/earthworks

- app/helpers/application_helper.rb
- app/views/catalog/_show_message.html.erb
- spec/features/unavailable_layer_spec.rb
Addresses concerns raised in ad hoc meeting about letting the user know that a layer is unavailable to download if no download options are present.
Deployed to dev successfully 
Closes #188
> adds in message if no downloads are available

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/earthworks.css.scss
- app/assets/stylesheets/modules/results.scss
- app/controllers/catalog_controller.rb
- app/views/catalog/_save_search.html.erb
- config/locales/blacklight.en.yml
- spec/factories/user.rb
- spec/features/saved_searches_spec.rb
- spec/rails_helper.rb
Previously, it was quite difficult to actually find how to save searches. This is now easier as "Save this search" and "Forget this search" are in the results tools
> Add saved search button to search results page

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
Re enables squash notify for EarthWorks. This was disabled because of an issue with the inclusion of the  `bin` directory as a linked_dir. 
See: https://github.com/kirs/capistrano/commit/e4f3b694ad0225ecc36a66b226afa2c8cd931656
> re-enable squash notify

- Gemfile
- Gemfile.lock
- Rakefile
- app/assets/javascripts/application.js
- app/assets/javascripts/modules/autocomplete.js
- app/assets/stylesheets/earthworks.css.scss
- app/assets/stylesheets/modules/typeahead.scss
- app/controllers/suggest_controller.rb
- config/application.rb
- config/blacklight.yml
- config/routes.rb
- config/solr_configs/schema.xml
- config/solr_configs/solrconfig.xml
- lib/suggest.rb
- lib/suggest/response.rb
- lib/suggest/search_helper.rb
- spec/controllers/suggest_controller_spec.rb
- spec/features/search_spec.rb
- spec/lib/suggest/response_spec.rb
- spec/lib/suggest/search_helper_spec.rb
> adds in autocomplete and spellcheck to application and Solr config

- app/controllers/wms_controller.rb
No longer needed, and now the same in GeoBlacklight.
See: https://github.com/geoblacklight/geoblacklight/blob/master/app/controllers/wms_controller.rb
> Remove overridding controller method.

- app/assets/javascripts/modules/autocomplete.js
- app/assets/stylesheets/modules/typeahead.scss
Library update was introduced in 7ae205be4a3e1337e996b50f4f5b8ebdd1c930fe. This
type of test is nearly impossible to created.
Closes #299
> Updates the typeahead code and styling to deal with an update.

- .travis.yml
Note ruby 2.4.1 does not work as-is.
> update to ruby 2.3.4

- config/deploy.rb
- config/deploy/dev.rb
- config/deploy/prod.rb
- config/deploy/stage.rb
explicitly states `server` name and `deploy_to`
> Updates capistrano to dept standards

- config/newrelic.yml
- config/settings.yml
There was a problem with -dev since it's now running in RAILS_ENV=production mode it was trying to do NewRelic monitoring but failing. This PR introduces an ENABLED flag.
> use Setting.NEWRELIC_ENABLED to enabled/disable NewRelic monitoring

- Gemfile.lock
Resolves missing icons here:
Closes #316
> update GeoBlacklight icons to get new types

- config/deploy/prod.rb
- config/deploy/stage.rb
- config/sidekiq.yml
this gives us 25 workers -- 5 processes each with 5 workers -- so that we can use the default 5 db connections in the pool as defined in `config/database.yml`
> explicitly configure sidekiq workers

- config/locales/blacklight.en.yml
- spec/features/page_title_spec.rb
This fixes an issue where a search result would provide a strange html title
> update page title for search results page

- Capfile
- Gemfile
- Gemfile.lock
This PR will refresh our shared_configs on any deploy. Right now, it's not doing it afaict.
> add shared_configs refreshes to capistrano deploys

- config/deploy/prod.rb
- config/schedule.rb
- config/sitemap.rb
Fixes #362 by changing `Blacklight.solr` to `Blacklight.default_index.connection` for the latest Blacklight release. It also installs a cron job to run `sitemap:refresh` once a week on both prod machines.
> update sitemap generation code and add cronjob for prod

- config/deploy.rb
Missed these in the cap deploy:
- add sitemap to whenever roles in deploy.rb
- add shared_configs:update hook to deploy.rb
> cap deploy fixes

- app/assets/stylesheets/modules/base_styles.scss
i'm _pretty_ sure this fix is all you need.
disclaimer: i did **not** test this fix locally because solr threw a weird error when i tried to spin it up.
> make sure leaflet's zoom control buttons aren't underlined

- scripts/geowebcache/add_gridsets.rb
Part of #472 
I've successfully tested this within our stage environment in conjunction with puppet #3754
After the puppet update is applied, this script can be run for each node
> adds script for updating tile caching gridsets

- Gemfile.lock
- scripts/geoserver/update_caching.rb
- scripts/geowebcache/add_gridsets.rb
Related to #472 
We need to remediate every layer already in GeoServer, to add WMS tile caching . This will set the Cache-Control max-age header, and unfortunately there is no way to do this globally.
> adds script to update caching for every layer

- scripts/geoserver/set_wms_default_style.rb
For some reason when the public geowebservices stack was restored this week, the default styling for vector data was somehow reset. This causes an error where the WMS service will not work (at all). 
This script is / was used to check each vector layer, and if it doesn't have an existing default style set it to `generic`
Needs to be run on each node.. commiting here for future usage.
> Add script that sets default style for vector data

- app/helpers/application_helper.rb
- spec/features/unavailable_layer_spec.rb
- spec/fixtures/solr_documents/stanford-paper-map.json
Without this, we will display a message to the user that the content is unavailable. Similar to our IIIF / availability that does not have GeoMonitor status checking
> Make sure oembed content is available for preview/download

- config/initializers/devise.rb
Resolves an issue where `email` was not valid for the `User` model.
> Add this shib thing, needed after doing shib migration from last year

- scripts/geoserver/set_wms_default_style.rb
Part of #636 
As a sampling of what it might do:
```
druid:zp324qp2900 is a vector; setting style (current: 'generic') to 'point'
druid:gy803bb5537 is a vector; setting style (current: 'generic') to 'polygon'
druid:ky867fv0017 is a vector; setting style (current: 'generic') to 'polygon'
druid:rx587qp9828 is a vector; defaultStyle is already set as polygon
druid:pt147bd6286 is a vector; setting style (current: 'generic') to 'polygon'
druid:yz347jp3502 is a vector; setting style (current: 'generic') to 'polygon'
druid:zs804mh1899 is a vector; setting style (current: 'generic') to 'polygon'
druid:vm491bz1561 is a vector; setting style (current: 'generic') to 'polygon'
druid:qv391sc1991 is a vector; setting style (current: 'generic') to 'polygon'
druid:ym783mg1598 is a vector; setting style …
```
> Update vector data with styling appropriate to the geom type

- config/solr_configs/solrconfig.xml
- spec/features/record_spec.rb
- spec/fixtures/solr_documents/actual-point1.json
Closes #644 
Adds an earthworks-processor that allows us to combine multiple processors.
Adds RemoveBlankFieldUpdateProcessorFactory to the earthworks-processor (in addition to the hashed id processor)
Note: these screenshots are using local fixtures and not production data.  I tested this w/ the ~4k NYU records locally and this fixed the issue for the 56 records that has blank publishers.
> Remove blank field values when documents are indexed.

- app/assets/stylesheets/modules/home.scss
- app/views/catalog/_home_text.html.erb
Some minor updates to give the page elements some vertical breathing room, while keeping overall page height the same:
- Reduced height of jumbotron search background and added some space between heading and search box. Also gave the jumbotron a light border for some definition.
- Removed the two horizontal rules and added some additional vertical whitespace instead.
- Added a light border to the Explore thumbnail images and the big map image. Again, just to give them a bit of definition against the page background (I'm bothered by the way the current Census data image blends into the page background.
- Centered the Explore image titles.
> Update styling of homepage

- app/assets/stylesheets/modules/header_navbar.scss
> Add an explicit width to the .navbar-brand to prevent the image-replaced text from showing

- config/locales/geoblacklight.en.yml
When https://github.com/geoblacklight/geoblacklight/pull/913 gets merged what we are looking for should automatically be dropped in place.
> Fixes #710 by updating keys for data relations widget

- config/initializers/sidekiq.rb
Reverts sul-dlss/earthworks#751
Turns out this wasn't duplicated `client/server` but no idea if we need this.
> Revert "Remove duplication on configure block"

- config/deploy/prod.rb
- config/schedule.rb
I guess it doesn't matter what enqueues these things, but seems nice to keep most of this on the worker box.
> Run the cron based job stuff on our worker machine

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- Add hiredis gem for faster redis connections
- Use redis as the cache store in production
> Use redis as the cache store

- Gemfile
- Gemfile.lock
This will unblock dependency updates and deploys until Redis is updated and we can update sidekiq to version 7. See: https://github.com/sul-dlss/operations-tasks/issues/3210#issuecomment-1302508219
> Keeps Sidekiq on version 6

- .github/workflows/ruby.yml
Hoping that this will bust the cache and fix the dependency issue affecting #956 (which appears to be https://github.com/actions/runner-images/issues/37)
> Use the builtin cache capability of setup-ruby action

- config/settings.yml
- Remove settings and contact info for UVa
- Update institutional contact information
this info powers this message when layers aren't available for download or preview:
this info is a best guess for the newer institutions; I figured that some value is better than nothing (it just shows a blank space in the alert text if there's nothing configured).
see #966
> Update institutional contact info

- Gemfile
- Gemfile.lock
- spec/lib/earthworks/harvester_spec.rb
Also removes GeoCombine from gemfile, since we can just use
GeoBlacklight's version.
> Update GeoBlacklight to v3.8.0

- .github/workflows/ruby.yml
- Gemfile
- Gemfile.lock
- scripts/geoserver/set_raster_styles.rb
- scripts/geoserver/set_wms_default_style.rb
- scripts/geoserver/update_caching.rb
- scripts/geowebcache/add_gridsets.rb
This removes the downstream dependency on patron, which needs
cURL headers in order to build correctly on Ubuntu machines.
The missing headers cause issues on both GitHub CI runners (https://github.com/actions/runner-images/issues/37)
and our automated deploys
(https://sul-ci-prod.stanford.edu/job/SUL-DLSS/job/earthworks/job/master/56/display/redirect).
> Pin faraday >= 2

- app/assets/javascripts/geoblacklight.js
> Prevent multiple worlds being shown on the leaflet map

- config/deploy/uat.rb
The only task that runs on the worker is the CheckLayerJob that
uses GeoMonitor to check layer availability; we don't need to
have both prod and UAT running this job since they're checking
the same set of layers and updating the same solr core.
Ref #942
> Remove deployment config for UAT worker box

- config/environments/production.rb
Taken from https://edgeguides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore
> Configure redis in a way to avoid timeout errors

- app/components/blacklight/icons/search_component.rb
This removes the dependency on the Redis cache, which seems to fail regularly with EOF
> Move search icon to a component

- Gemfile
- Gemfile.lock
- config/schedule.rb
- lib/tasks/earthworks.rake
Closes #639 
<s>Blocked by https://github.com/OpenGeoMetadata/GeoCombine/pull/169</s>
Tested by deploying to stage and running the rake tasks, which completed successfully.
> Add scheduled indexing from OpenGeoMetadata

- Jenkinsfile
This will allow iterative refinement of the Geoblacklight-4
compatible version of earthworks without needing to pause
dependency updates in production.
It's expected that this work will be finished and reverted by
the start of the Earthworks workcycle on 6/24.
If this is merged, https://github.com/sul-dlss/shared_configs/pull/2194
and https://github.com/sul-dlss/shared_configs/pull/2193 are
also needed to point the app at new compatible solr cores using
the Aardvark schema.
> Decouple CD for stage/UAT and connect to Geoblacklight v4 branch

- config/routes.rb
To help monitor what's going on in the application the sidekiq web interface is mounted at `/queues/`.
Similar to other applications (e.g. H2) access to this route will be blocked upstream in Apache configuration managed by Puppet. See: https://github.com/sul-dlss/puppet/pull/10982 
Closes #369
> Enable sidekiq-web at /queues

- README.md
- docker-compose.yml
Solr core names differ from solr-wrapper to Docker.  This may reduce some confusion.
This makes them the same so the README instructions are correct.
> Update name of solr-core in docker

- config/initializers/blacklight_dynamic_sitemap.rb
Document unique ids are just called `id` in Aardvark
> Update sitemap to use the correct ID field

- Gemfile
- Gemfile.lock
- app/components/earthworks/searchworks_url.html.erb
- app/components/earthworks/searchworks_url.rb
- app/controllers/catalog_controller.rb
- app/helpers/earthworks_geoblacklight_helper.rb
- app/models/solr_document.rb
- spec/features/searchworks_url_spec.rb
- spec/fixtures/solr_documents/stanford-ts545zc6250.json
Fixes #310 and follow on from https://github.com/sul-dlss/searchworks_traject_indexer/pull/1490 
If searchworks url is present in solr document, render on the page.
Todo:
With link:
http://localhost:3000/catalog/stanford-dt131hw5005
> Add searchworks url to toolbar

- app/views/catalog/_show_message.html.erb
- config/settings.yml
closes #418 
Tested by updating the settings.yml file to remove line 301 and then looked at http://localhost:3000/catalog/mit-001145244.
> add fallback email if there isn't an institution email

- config/initializers/okcomputer.rb
- config/schedule.rb
- config/settings.yml
- lib/tasks/earthworks.rake
Fixes #205 -- add a scheduled rake task for clearing stale download files
Configured to run daily and clear any files not accessed in the last 2 weeks (time period configurable in settings).
Tested find command manually on server (but nothing deleted).
~~See also https://github.com/sul-dlss/shared_configs/pull/2220 which is required first.~~
~~Note, we may want to set the download cache directory in stage shared configs here: https://github.com/sul-dlss/shared_configs/blob/earthworks-stage/config/settings/production.yml#L1  to match what is in in prod: https://github.com/sul-dlss/shared_configs/blob/earthworks-prod/config/settings/production.yml#L1~~
~~it is currently set to `nil` in stage, which will cause problems with this cron job~~
> rake task and cron job for clearing stale downloads

- lib/earthworks/harvester.rb
- spec/lib/earthworks/harvester_spec.rb
as part of that, update Earthworks::Harvester spec to consistently use the Aardvark schema (since the app has already switched over to that schema and we have to use one of its fields in this work)
part of https://github.com/sul-dlss/earthworks/issues/1089
> Earthworks::Harvester - skip restricted records from other institutions

- config/solr_configs/synonyms.txt
Addresses #41 .
**What this pull request does:**
Copies the additional synonym lines from the following files under the originally referenced OpenGeoPortal configuration: 
https://github.com/OpenGeoportal/ogpSolrConfig/tree/master/ogpSolrConfig/SolrConfig
These include synonyms for LCSH terms (e.g. mapping "mountains" and "peaks" to each other so that any query for mountains would include both mountains and peaks in the query after synonyms have been applied), synonyms for ISO  (e.g. mapping "History" and "ancestry" to each other), and State names (e.g. mapping Wyoming and "WY " - with a trailing space - to each other). 
An additional pull request will apply these changes to sul-solr-configs starting with stage. 
**Using synonyms in Solr**
One of the LCSH mappings is between mountains and …
> Adding synonym values based on OGP examples

- Gemfile.lock
fixes https://github.com/sul-dlss/earthworks/issues/1098
displays without error when no search terms are given and no facet is chosen:
> update to latest geoblacklight

- Gemfile
- Gemfile.lock
Now that https://github.com/geoblacklight/geoblacklight/pull/1441 has been merged we should probably be using main?
> Use geoblacklight main

- .solr_wrapper
- docker-compose.yml
This aligns the solr_wrapper and docker solr versions to match what we are using in production: v8.11.2
> Align solr versions

- Gemfile
- Gemfile.lock
- app/helpers/earthworks_geoblacklight_helper.rb
Now that Geoblacklight has BL8 updates on main, we need to stop
pointing at it unless we want to deploy those changes and break
our own app.
> Stop pointing at Geoblacklight's main branch

- config/settings.yml
See https://github.com/geoblacklight/geoblacklight/issues/1446. Since we don't have the fix implemented the icons aren't showing up. Adding the ICON_MAPPING fixes the icons. 
For the line `:INFO_FORMAT: "application/json"` see https://github.com/geoblacklight/geoblacklight/issues/612 and https://github.com/geoblacklight/geoblacklight/pull/1429. Switching to application/json allows highlighting on map when clicked.
> fix legacy icons, info_format

- app/assets/stylesheets/earthworks.css
- app/components/earthworks/header_icons_component.html.erb
- app/components/earthworks/header_icons_component.rb
- app/components/earthworks/search_result_component.html.erb
- app/components/earthworks/search_result_component.rb
- app/controllers/catalog_controller.rb
> Bl8 results component

- app/components/earthworks/alert_component.html.erb
- app/components/earthworks/alert_component.rb
- app/views/layouts/catalog_result.html.erb
- config/locales/en.yml
- spec/features/georeference_spec.rb
- spec/fixtures/solr_documents/public_iiif_princeton.json
> Bl8 georeference alert

- app/assets/stylesheets/earthworks.css
- app/controllers/catalog_controller.rb
- app/views/catalog/_document_split.html.erb
- app/views/catalog/_search_header.html.erb
update default number of result to 20. Closes #1171
Quick notes
- app/views/catalog/_document_split.html.erb is overriding and override from geoblacklight. The only real change is to add in `   <%= render blacklight_config.view_config(document_index_view_type).search_header_component.new %>` above turbo-frame
- app/views/catalog/_search_header.html.erb is an override from blacklight. In blacklight it renders the search_header_component which has a partial with ```<%= render 'did_you_mean' %>
<%= render 'sort_and_per_page' %>``` so I just moved everything into this file and removed `sort_and_per_page` which is a partial where the only thing in it is `render blacklight_config.view_config(document_index_view_type).search_header_component.new`
> move search header into document split

- app/controllers/catalog_controller.rb
Fixes #1126 
If you don't add the metadata toolbar link, the action is not available, resulting in an exception if you hit the `/metadata` link manually.  This adds the link if metadata is available to render.
Similar to what is done here: https://github.com/geoblacklight/geoblacklight/blob/032115d9960c3559124d2b4d03a79f9f245a7012/lib/generators/geoblacklight/templates/catalog_controller.rb#L302
> shows metadata modal link in toolbar if metadata available

- app/assets/stylesheets/earthworks.css
- app/components/blacklight/icons/search_component.rb
Right now the text is not displaying so as a stop gap I had the icon display the text. This has been fixed in blacklight but the css isn't available until a new release is published on npm.
> update search bar to match figma

- app/assets/stylesheets/earthworks.css
When doing this locally I was using bl8.3.1 which fixed the missing name in classes for icons. This will fix how the search button is displaying on uat.
> fix css for search button

- app/components/earthworks/download_links_component.html.erb
fixes https://github.com/sul-dlss/earthworks/issues/1201
here's a test on localhost where i hacked in the offending text from the issue description by hardcoding it in the component class' `download_link_file` method:
i wasn't sure whether an inline style was acceptable -- went that way because i saw it used elsewhere in the same `.erb`.  but happy to turn into a class if that's better.
> DownloadLinksComponent: add download button div class to prevent link text colliding with other page elements

- app/assets/stylesheets/earthworks.css
- app/components/earthworks/search_result_component.html.erb
- app/javascript/controllers/description_controller.js
- app/javascript/controllers/expandcollapse_controller.js
- app/views/catalog/_sort_and_per_page.html.erb
An approach w more stimulus
Builds on a would replace #1234
> Expand collapse 3

- app/components/blacklight/top_navbar_component.html.erb
This matches Figma (or at least gets closer).
Before:
After:
Figma:
> Reduce the app header vertical padding slightly

- app/assets/stylesheets/earthworks.css
- app/components/blacklight/top_navbar_component.html.erb
closes #1243 
The reason the screenshot shows a sunet because my local doesn't have the display name. By default it will show the display name and fall back to the sunet if the display name doesn't exist.
> create logout dropdown

- app/components/blacklight/top_navbar_component.html.erb
When you bookmark something the parentheses are removed. This PR fixes that.
> fix parentheses in header

- Gemfile
- Gemfile.lock
- spec/features/axe_spec.rb
- Bookmark tests are commented out until bookmarks are added back in
- Line 18-21 keeps failing on 3.2 CI. It works fine locally with both ruby versions. I am commenting out until we remove 3.2 from the testing CI.
> Bl8 axe spec

- app/assets/stylesheets/earthworks.css
Fixes #1262 : change active facet background color, font and border to match the header
**Before:**
**After:**
Testing note: this will only work when a new version of Blacklight is released and Earthworks is updated to use it.
> Change facet background/text color

- app/assets/stylesheets/earthworks.css
We don't need this -- it came from a bad rebase on https://github.com/sul-dlss/earthworks/pull/1270
The CSS just below is sufficient to cover this.
> Follow on for facet color background

- app/assets/stylesheets/earthworks.css
This gives slightly more content area on small screens (bootstrap default) and avoids the need for an extra rule
> Use additive style rather than subtractive

- app/views/layouts/catalog_result.html.erb
closes #1283 
before 
https://github.com/sul-dlss/earthworks/issues/1283#issue-2492985091
after
> update header tools to be even

- app/assets/stylesheets/earthworks.css
- config/locales/blacklight.en.yml
Closes https://github.com/sul-dlss/earthworks/issues/1278
(button color pending in another PR)
> Revise text and layout for search widgets on small screens

- app/assets/stylesheets/earthworks.css
Part of #1279
Does not cover the resizing of the magnifying glass icon; I will wait until we merge code around the `search_component` for that. Not closing the ticket yet.
> Change padding and alignment for search bar

- app/assets/stylesheets/earthworks.css
> make box shadow appear on right and left

- app/assets/stylesheets/earthworks.css
- app/views/catalog/_sort_and_per_page.html.erb
Fixes #1341 - make expand/collapse buttons blue
With this PR:
> 1343 Make expand/collapse buttons blue

- app/assets/stylesheets/earthworks.css
- app/views/catalog/_sort_and_per_page.html.erb
@dbranchini indicated that this should go to centered below large, not medium. So now we have both:
> Center the search widgets below size lg screens

- app/components/recently_added_list_component.html.erb
- app/components/recently_added_list_component.rb
- app/views/catalog/_home_text.html.erb
- config/locales/en.yml
- spec/components/recently_added_list_component_spec.rb
> Modify RecentlyAddedListComponent and its copy

- app/assets/stylesheets/earthworks.css
- app/components/facet_group_component.html.erb
- app/components/facet_group_component.rb
- app/controllers/catalog_controller.rb
- app/helpers/earthworks_blacklight_helper.rb
- app/javascript/controllers/maptogglebutton_controller.js
- app/javascript/controllers/searchmapcontainer_controller.js
- app/views/catalog/_document_split.html.erb
- app/views/catalog/_home_text.html.erb
> 1329 map collapse

- app/views/catalog/_document_split.html.erb
closes #1383
There is a way to keep the turbo-frame but it requires adding target="_top" to the link which would require a bunch of overrides in blacklight. I think pushing this down the road is fine.
We could also add a Turbo.visit javascript but again it seems like something better if it is done as part of https://github.com/geoblacklight/geoblacklight/issues/1424
> remove turbo-frame for results/bookmark links

- app/assets/stylesheets/earthworks.css
> Ensure the page cannot be shorter than the viewport height

- config/settings.yml
Once the GeoBlacklight PR goes through, we can make this change locally on EarthWorks.
Closes #1300
> replacing KMZ with CSV as download option

- config/routes.rb
Bots were hitting the show route, which is not normally used. See https://github.com/projectblacklight/blacklight/pull/3318
> Only create the useful bookmark routes

- app/components/blacklight/top_navbar_component.html.erb
- app/components/dropdown_component.rb
- config/importmap.rb
- lib/earthworks/harvester.rb
> Capitalize the W in EarthWorks

- app/assets/stylesheets/earthworks.css
The "Other" option in the resource class facet is a local component,
so it was using a blue color instead of the standard gray. This
ensures that custom icon components get the right color.
> Ensure custom facet icons get the correct fill color

- app/assets/stylesheets/earthworks.css
Embedded content has a border provided by sul-embed's own
stylesheet. It adds some nice contrast to the page, so I figured
we could make the non-embed viewers match.
> Add a border to the leaflet viewer to match sul-embed

- app/components/blacklight/date_facet_hierarchy_component.rb
- app/presenters/date_facet_item_presenter.rb
Fixes #1411
Also formats to remove leading zeroes.
> Update date hierarchy faceting to correct facet counts

- app/assets/stylesheets/earthworks.css
This overrides a geoblacklight style to prevent extra margin from being added to item descriptions.
> Only add margin to consecutive paragraphs

- app/components/document_component.html.erb
- app/helpers/earthworks_blacklight_helper.rb
This fixes some alignment issues and removes some redundant
classes.
Closes #1318
See also https://github.com/geoblacklight/geoblacklight/pull/1607
> Remove row > row nesting

- Gemfile
- Gemfile.lock
- config/importmap.rb
- package-lock.json
- package.json
> Upgrade to Blacklight 8.4.0

- lib/tasks/earthworks.rake
https://github.com/geoblacklight/geoblacklight/commit/a972289b2d5ee3b78d51d4c27642a64c21e6b689
changed the names of some rake tasks in Geoblacklight. I updated
one in #1435, but missed some other instances of it.
> Update names of rake tasks

- app/components/also_available_component.html.erb
- app/components/document/sidebar_component.html.erb
- app/components/document/sidebar_component.rb
- Refactor sidebar component and combine secondary portions
Before:
After:
Part of #1437
> Sidebar display fixes

- app/views/layouts/blacklight/base.html.erb
Fixes #1431.
We updated the relevant component in Blacklight, but weren't
actually rendering it.
> Use blacklight's SkipLinksComponent

- app/assets/stylesheets/earthworks.css
- app/views/layouts/blacklight/base.html.erb
With 9254fbf, we deferred non-critical CSS by loading it at the
end of the page. However, this had an unintended side-effect:
making the viewer CSS load last in the cascade.
This meant that fixes like https://github.com/geoblacklight/geoblacklight/commit/12bd71fbd36d054353e5047328455966a049b85a
had no effect, because they were loaded as part of geoblacklight's
CSS and then overridden by the viewer's own CSS.
This change switches to the strategy outlined in
https://web.dev/articles/defer-non-critical-css,
which defers CSS loading but reverts to the original DOM order
for the styles, preserving the ability to affect Leaflet's
styles in our own without resorting to !important.
It also removes one instance where we were using !important
to get around this problem.
> Defer non-critical CSS without changing cascade order

- app/components/blacklight/top_navbar_component.html.erb
The 2025-01-07 release of component library adds css that changes the hamburger icon to an X when the menu is open, but it requires that the initial state include `collapsed` class on the button. See https://github.com/sul-dlss/component-library/compare/v2024-12-18...v2025-01-07#diff-02bda451f4ad8d9385f3c922c6ed0ed1cdce7c820bb3e86f8f0ccafa4ebf5889L68-R74
This PR:
Main:
> Add collapsed class to navbar-toggler button

- app/assets/stylesheets/earthworks.css
- app/views/layouts/blacklight/base.html.erb
> update component library, remove pagination css

- Gemfile
- Gemfile.lock
- app/controllers/restricted_proxy_controller.rb
- config/initializers/config.rb
- config/settings.yml
- spec/controllers/restricted_proxy_controller_spec.rb
This PR does a couple things:
1. fixes proxy response, the old way was returning a LocalJumpError https://app.honeybadger.io/projects/49895/faults/118259904. This is fixed by https://github.com/sul-dlss/earthworks/pull/1484/files#diff-4d95f4d583481eb175bbf04811a2ac3b579ea7c126965760942081923ed4da09R30 
2. Authorizes the user with a token from stacks instead of having to log in with shibboleth
3. Allows cross origin so sul-embed can request proxy
Part of https://github.com/sul-dlss/sul-embed/issues/2757
> Update proxy to work with sul-embed

- config/initializers/bot_challenge_page.rb
Earthworks side of https://github.com/sul-dlss/stanford-arclight/pull/1197, which has fixed our SearchWorks mini-bento issue.
> Use the predicate method to check format in bot challenge config
